---
abstract: 'Build and install libyaml, a C-based YAML parser and emitter'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Alien::Base::ModuleBuild: 0.002
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-LibYAML
requires:
  Alien::Base: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/rsimoes/alien-libyaml/issues
  homepage: https://metacpan.org/release/Alien-LibYAML
  repository: git://github.com/rsimoes/alien-libyaml.git
version: v0.0.5
